sudo: required

dist: trusty

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - sudo add-apt-repository -y ppa:ondrej/mysql-5.7
  - sudo apt-get update -qq
  - sudo apt-get install mysql-server-5.7 mysql-client-5.7
  - sudo service mysql stop
  - sudo rm -Rf /var/lib/mysql
  - sudo mysqld --initialize-insecure --user=mysql
  - sudo service mysql start

language: php

php:
  - 7.0
  - 7.1

services:
  - mysql

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
  - mysql -e 'create database laravel_migrate_fresh;' -uroot

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
